/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const ORACLE_SQL_DDL = `-- ====================================================================
-- PROJECT TITLE: Smart Agricultural Produce Collection & Management System
-- ORACLE DATABASE CAPSTONE DDL & DML SCRIPTS
-- COMPATIBLE WITH: Oracle Database 19c / 21c / APEX Cloud
-- ====================================================================

-- DROP STATEMENTS (For Clean Re-runs)
-- DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS;
-- DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
-- DROP TABLE ORDERS CASCADE CONSTRAINTS;
-- DROP TABLE INVENTORY CASCADE CONSTRAINTS;
-- DROP TABLE PRODUCE_COLLECTIONS CASCADE CONSTRAINTS;
-- DROP TABLE PRODUCE CASCADE CONSTRAINTS;
-- DROP TABLE PRODUCE_CATEGORIES CASCADE CONSTRAINTS;
-- DROP TABLE BUYERS CASCADE CONSTRAINTS;
-- DROP TABLE FARMERS CASCADE CONSTRAINTS;
-- DROP TABLE PUBLIC_HOLIDAYS CASCADE CONSTRAINTS;
-- DROP SEQUENCE FARMER_SEQ;
-- DROP SEQUENCE BUYER_SEQ;
-- DROP SEQUENCE CATEGORY_SEQ;
-- DROP SEQUENCE PRODUCE_SEQ;
-- DROP SEQUENCE COLLECTION_SEQ;
-- DROP SEQUENCE INVENTORY_SEQ;
-- DROP SEQUENCE ORDER_SEQ;
-- DROP SEQUENCE PAYMENT_SEQ;
-- DROP SEQUENCE HOLIDAY_SEQ;
-- DROP SEQUENCE AUDIT_LOG_SEQ;


-- ====================================================================
-- 1. SEQUENCES FOR AUTOMATIC PRIMARY KEY GENERATION
-- ====================================================================
CREATE SEQUENCE FARMER_SEQ START WITH 1006 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BUYER_SEQ START WITH 2005 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CATEGORY_SEQ START WITH 5 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PRODUCE_SEQ START WITH 306 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COLLECTION_SEQ START WITH 5005 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INVENTORY_SEQ START WITH 6006 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ORDER_SEQ START WITH 7004 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ START WITH 8005 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HOLIDAY_SEQ START WITH 905 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 9504 INCREMENT BY 1 NOCACHE;


-- ====================================================================
-- 2. TABLE CREATIONS & CONSTRAINTS
-- ====================================================================

-- TABLE: PUBLIC_HOLIDAYS
CREATE TABLE PUBLIC_HOLIDAYS (
    HOLIDAY_ID NUMBER NOT NULL,
    HOLIDAY_NAME VARCHAR2(150) NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    IS_COLLECTION_BLOCKED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PUBLIC_HOLIDAYS PRIMARY KEY (HOLIDAY_ID),
    CONSTRAINT UQ_HOLIDAY_DATE UNIQUE (HOLIDAY_DATE),
    CONSTRAINT CK_IS_COLLECTION_BLOCKED CHECK (IS_COLLECTION_BLOCKED IN ('Y', 'N'))
);

-- TABLE: FARMERS
CREATE TABLE FARMERS (
    FARMER_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100),
    NATIONAL_ID VARCHAR2(50) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE NOT NULL,
    REGION VARCHAR2(100) NOT NULL,
    COOPERATIVE_NAME VARCHAR2(150),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT PK_FARMERS PRIMARY KEY (FARMER_ID),
    CONSTRAINT UQ_FARMER_NATIONAL_ID UNIQUE (NATIONAL_ID),
    CONSTRAINT CK_FARMER_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'INACTIVE'))
);

-- TABLE: BUYERS
CREATE TABLE BUYERS (
    BUYER_ID NUMBER NOT NULL,
    COMPANY_NAME VARCHAR2(200) NOT NULL,
    CONTACT_PERSON VARCHAR2(150) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    CREDIT_LIMIT NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    BALANCE NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT PK_BUYERS PRIMARY KEY (BUYER_ID),
    CONSTRAINT CK_BUYER_STATUS CHECK (STATUS IN ('ACTIVE', 'BLACKLISTED', 'INACTIVE')),
    CONSTRAINT CK_BUYER_CREDIT CHECK (CREDIT_LIMIT >= 0)
);

-- TABLE: PRODUCE_CATEGORIES
CREATE TABLE PRODUCE_CATEGORIES (
    CATEGORY_ID NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(400),
    STORAGE_TEMP_C NUMBER(4,1),
    CONSTRAINT PK_PRODUCE_CATEGORIES PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

-- TABLE: PRODUCE
CREATE TABLE PRODUCE (
    PRODUCE_ID NUMBER NOT NULL,
    PRODUCE_NAME VARCHAR2(150) NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    BASE_PRICE_PER_KG NUMBER(10,2) NOT NULL,
    SKU VARCHAR2(50) NOT NULL,
    EXPIRY_DAYS NUMBER DEFAULT 30 NOT NULL,
    CONSTRAINT PK_PRODUCE PRIMARY KEY (PRODUCE_ID),
    CONSTRAINT UQ_PRODUCE_NAME UNIQUE (PRODUCE_NAME),
    CONSTRAINT UQ_PRODUCE_SKU UNIQUE (SKU),
    CONSTRAINT FK_PRODUCE_CATEGORY FOREIGN KEY (CATEGORY_ID) 
        REFERENCES PRODUCE_CATEGORIES(CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT CK_BASE_PRICE CHECK (BASE_PRICE_PER_KG > 0)
);

-- TABLE: PRODUCE_COLLECTIONS
CREATE TABLE PRODUCE_COLLECTIONS (
    COLLECTION_ID NUMBER NOT NULL,
    FARMER_ID NUMBER NOT NULL,
    PRODUCE_ID NUMBER NOT NULL,
    COLLECTION_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    QUANTITY_KG NUMBER(10,2) NOT NULL,
    PRICE_PER_KG NUMBER(10,2) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    GRADE VARCHAR2(2) NOT NULL,
    MOISTURE_CONTENT NUMBER(4,2),
    HOLIDAY_CHECK VARCHAR2(20) DEFAULT 'PASSED' NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_PRODUCE_COLLECTIONS PRIMARY KEY (COLLECTION_ID),
    CONSTRAINT FK_COLLECTION_FARMER FOREIGN KEY (FARMER_ID) 
        REFERENCES FARMERS(FARMER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COLLECTION_PRODUCE FOREIGN KEY (PRODUCE_ID) 
        REFERENCES PRODUCE(PRODUCE_ID) ON DELETE CASCADE,
    CONSTRAINT CK_COLLECTION_QTY CHECK (QUANTITY_KG > 0),
    CONSTRAINT CK_COLLECTION_PRICE CHECK (PRICE_PER_KG > 0),
    CONSTRAINT CK_COLLECTION_GRADE CHECK (GRADE IN ('A', 'B', 'C'))
);

-- TABLE: INVENTORY
CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER NOT NULL,
    PRODUCE_ID NUMBER NOT NULL,
    STOCK_ON_HAND NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    RESERVED_STOCK NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    AVAILABLE_STOCK NUMBER(12,2) GENERATED ALWAYS AS (STOCK_ON_HAND - RESERVED_STOCK) VIRTUAL,
    LOCATION_BAY VARCHAR2(50) NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INVENTORY PRIMARY KEY (INVENTORY_ID),
    CONSTRAINT UQ_INVENTORY_PRODUCE UNIQUE (PRODUCE_ID),
    CONSTRAINT FK_INVENTORY_PRODUCE FOREIGN KEY (PRODUCE_ID) 
        REFERENCES PRODUCE(PRODUCE_ID) ON DELETE CASCADE,
    CONSTRAINT CK_STOCK_ON_HAND CHECK (STOCK_ON_HAND >= 0),
    CONSTRAINT CK_RESERVED_STOCK CHECK (RESERVED_STOCK >= 0)
);

-- TABLE: ORDERS
CREATE TABLE ORDERS (
    ORDER_ID NUMBER NOT NULL,
    BUYER_ID NUMBER NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    ORDER_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    SHIPPING_ADDRESS VARCHAR2(300) NOT NULL,
    EXPECTED_DELIVERY_DATE DATE,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_BUYER FOREIGN KEY (BUYER_ID) 
        REFERENCES BUYERS(BUYER_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ORDER_STATUS CHECK (ORDER_STATUS IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT CK_ORDER_AMOUNT CHECK (TOTAL_AMOUNT >= 0)
);

-- TABLE: PAYMENTS
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER NOT NULL,
    SOURCE_TYPE VARCHAR2(20) NOT NULL,
    SOURCE_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,
    TRANSACTION_REFERENCE VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT PK_PAYMENTS PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT UQ_TRANSACTION_REF UNIQUE (TRANSACTION_REFERENCE),
    CONSTRAINT CK_PAYMENT_SOURCE CHECK (SOURCE_TYPE IN ('COLLECTION', 'ORDER')),
    CONSTRAINT CK_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CHEQUE')),
    CONSTRAINT CK_PAYMENT_STATUS CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_PAYMENT_AMOUNT CHECK (AMOUNT > 0)
);

-- TABLE: AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    LOG_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,
    ACTION_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TABLE_NAME VARCHAR2(100) NOT NULL,
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    IP_ADDRESS VARCHAR2(45) NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);


-- ====================================================================
-- 3. PL/SQL DATABASE TRIGGERS FOR SYSTEM LOGIC
-- ====================================================================

-- TRIGGER 1: BI_PRODUCE_COLLECTIONS_CALC
-- Automatically calculates total collection amount and performs holiday validation
-- before inserts on PRODUCE_COLLECTIONS.
CREATE OR REPLACE TRIGGER BI_PRODUCE_COLLECTIONS_CALC
BEFORE INSERT ON PRODUCE_COLLECTIONS
FOR EACH ROW
DECLARE
    v_holiday_count NUMBER;
    v_blocked CHAR(1);
BEGIN
    -- Automatic derivation of Total Amount
    :NEW.TOTAL_AMOUNT := :NEW.QUANTITY_KG * :NEW.PRICE_PER_KG;
    
    -- Autogenerate primary key if not supplied
    IF :NEW.COLLECTION_ID IS NULL THEN
        SELECT COLLECTION_SEQ.NEXTVAL INTO :NEW.COLLECTION_ID FROM DUAL;
    END IF;

    -- Oracle Business Rule Trigger: Check for Public Holidays
    SELECT COUNT(*), MAX(IS_COLLECTION_BLOCKED)
    INTO v_holiday_count, v_blocked
    FROM PUBLIC_HOLIDAYS
    WHERE TRUNC(HOLIDAY_DATE) = TRUNC(:NEW.COLLECTION_DATE);

    IF v_holiday_count > 0 AND v_blocked = 'Y' THEN
        -- Set warnings or raise custom error
        :NEW.HOLIDAY_CHECK := 'WARNING';
        -- Optional: To strictly enforce and abort, uncomment below:
        -- raise_application_error(-20001, 'COLLECTION ATTEMPTED ON BLOCKED PUBLIC HOLIDAY: ' || :NEW.COLLECTION_DATE);
    ELSE
        :NEW.HOLIDAY_CHECK := 'PASSED';
    END IF;
END;
/

-- TRIGGER 2: AI_PRODUCE_COLLECTIONS_INVENTORY
-- Automatically updates Stock on Hand in INVENTORY and registers a pending PAYMENT
-- after a new Collection is registered.
CREATE OR REPLACE TRIGGER AI_PRODUCE_COLLECTIONS_INVENTORY
AFTER INSERT ON PRODUCE_COLLECTIONS
FOR EACH ROW
DECLARE
    v_inv_exists NUMBER;
    v_txn_ref VARCHAR2(100);
BEGIN
    -- 1. Manage Inventory Stock Levels
    SELECT COUNT(*) INTO v_inv_exists FROM INVENTORY WHERE PRODUCE_ID = :NEW.PRODUCE_ID;
    
    IF v_inv_exists > 0 THEN
        UPDATE INVENTORY 
        SET STOCK_ON_HAND = STOCK_ON_HAND + :NEW.QUANTITY_KG,
            LAST_UPDATED = SYSTIMESTAMP
        WHERE PRODUCE_ID = :NEW.PRODUCE_ID;
    ELSE
        INSERT INTO INVENTORY (INVENTORY_ID, PRODUCE_ID, STOCK_ON_HAND, RESERVED_STOCK, LOCATION_BAY, LAST_UPDATED)
        VALUES (INVENTORY_SEQ.NEXTVAL, :NEW.PRODUCE_ID, :NEW.QUANTITY_KG, 0.00, 'BAY-AUTO', SYSTIMESTAMP);
    END IF;

    -- 2. Autocreate Pending Farmer Disbursement Payment
    v_txn_ref := 'TXN-BK-AUTO-' || :NEW.COLLECTION_ID;
    INSERT INTO PAYMENTS (PAYMENT_ID, SOURCE_TYPE, SOURCE_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_REFERENCE, STATUS)
    VALUES (PAYMENT_SEQ.NEXTVAL, 'COLLECTION', :NEW.COLLECTION_ID, SYSDATE, :NEW.TOTAL_AMOUNT, 'BANK_TRANSFER', v_txn_ref, 'PENDING');
END;
/

-- TRIGGER 3: AUDITING TRIGGERS (Automated Oracle Audit Log)
-- Generates automated Oracle security audits for changes in Farmers or Collections.
CREATE OR REPLACE TRIGGER TRG_AUDIT_FARMERS
AFTER INSERT OR UPDATE OR DELETE ON FARMERS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
    v_old CLOB := NULL;
    v_new CLOB := NULL;
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_new := '{"FARMER_ID":' || :NEW.FARMER_ID || ',"NAME":"' || :NEW.FIRST_NAME || ' ' || :NEW.LAST_NAME || '","STATUS":"' || :NEW.STATUS || '"}';
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_old := '{"FARMER_ID":' || :OLD.FARMER_ID || ',"STATUS":"' || :OLD.STATUS || '"}';
        v_new := '{"FARMER_ID":' || :NEW.FARMER_ID || ',"STATUS":"' || :NEW.STATUS || '"}';
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_old := '{"FARMER_ID":' || :OLD.FARMER_ID || ',"NAME":"' || :OLD.FIRST_NAME || ' ' || :OLD.LAST_NAME || '"}';
    END IF;

    INSERT INTO AUDIT_LOG (LOG_ID, USERNAME, ACTION, ACTION_TIMESTAMP, TABLE_NAME, OLD_VALUE, NEW_VALUE, IP_ADDRESS)
    VALUES (AUDIT_LOG_SEQ.NEXTVAL, COALESCE(SYS_CONTEXT('USERENV', 'SESSION_USER'), 'ADMIN'), v_action, SYSTIMESTAMP, 'FARMERS', v_old, v_new, '127.0.0.1');
END;
/
`;
